Repository AnguHashBlog/angular, pull requests merged in 2024-03, with the labels that each got.

#4 hashnode blog url changed to 'hashnode-blog.hashnodeng.com'
  angular-app/src/app/graphql.operations.ts
Labels: enhancement

#17 latest updates
  CONTRIBUTING.md
  LICENSE
  README.md
  anguhashblog.png
  angular-app/README.md
  angular-app/dist/browser/chunk-RSXKKZI5.js
  angular-app/dist/browser/index.html
  angular-app/dist/browser/main-5KYMJBWH.js
  angular-app/src/app/components/footer/footer.component.html
  angular-app/src/app/components/header/header.component.ts
  angular-app/src/app/components/post-details/post-details.component.spec.ts
  angular-app/src/app/graphql.operations.ts
  angular-app/src/app/partials/follow-dialog/follow-dialog.component.html
  angular-app/src/assets/images/anguhashblog-logo.jpg
  angular-app/src/index.html
Labels: 🌟feature, 📁 file structure

#23 feat(icon): dailydev custom SVG icon added
  angular-app/src/assets/icons/dailydev.svg
Labels: 🌟feature, 🖼️ images & icons

#29 Main
  README.md
Labels: 📄 documentation, 🖼️ images & icons

#35 Change blog url
  angular-app/src/app/app.component.html
  angular-app/src/app/app.component.ts
  angular-app/src/app/components/footer/footer.component.ts
  angular-app/src/app/components/header/header.component.html
  angular-app/src/app/components/header/header.component.scss
  angular-app/src/app/components/header/header.component.ts
  angular-app/src/app/components/layout/layout.component.html
  angular-app/src/app/components/post-details/post-details.component.html
  angular-app/src/app/components/post-details/post-details.component.scss
  angular-app/src/app/components/post-details/post-details.component.ts
  angular-app/src/app/components/posts/posts.component.ts
  angular-app/src/app/components/series/series.component.ts
  angular-app/src/app/components/sidenav/sidenav.component.ts
  angular-app/src/app/graphql.operations.ts
  angular-app/src/app/partials/follow-dialog/follow-dialog.component.html
  angular-app/src/app/partials/settings-dialog/settings-dialog.component.html
  angular-app/src/app/partials/settings-dialog/settings-dialog.component.scss
  angular-app/src/app/partials/settings-dialog/settings-dialog.component.spec.ts
  angular-app/src/app/partials/settings-dialog/settings-dialog.component.ts
  angular-app/src/app/services/blog.service.ts
  angular-app/src/app/services/modal.service.ts
  angular-app/src/styles.scss
Labels: 🌟feature, 🛰️ apollo angular, GraphGL, RxJS, 🎨 styling, 📁 file structure

#38 Update styles.scss
  angular-app/src/styles.scss
Labels: 🐛 bug, 🖼️ images & icons, 🎨 styling

#39 feature: Add pagination or load more for blog posts in - posts & series
  angular-app/src/app/components/posts/posts.component.html
  angular-app/src/app/components/posts/posts.component.scss
  angular-app/src/app/components/posts/posts.component.ts
  angular-app/src/app/components/series/series.component.html
  angular-app/src/app/components/series/series.component.scss
  angular-app/src/app/components/series/series.component.ts
  angular-app/src/app/directives/infinite-scroll.directive.spec.ts
  angular-app/src/app/directives/infinite-scroll.directive.ts
  angular-app/src/app/graphql.operations.ts
  angular-app/src/app/models/blog-info.ts
  angular-app/src/app/services/blog.service.ts
Labels: 🌟feature, 🛰️ apollo angular, GraphGL, RxJS, 🚦signals, 📁 file structure, custom directive

#42 fix(series): load more posts only from the series
  angular-app/src/app/components/posts/posts.component.scss
  angular-app/src/app/components/posts/posts.component.ts
  angular-app/src/app/components/series/series.component.html
  angular-app/src/app/components/series/series.component.scss
  angular-app/src/app/components/series/series.component.ts
  angular-app/src/app/graphql.operations.ts
  angular-app/src/app/services/blog.service.ts
Labels: 🐛 bug, 🎨 styling

#45 fix(models): placing the interface in the sorrect file
  angular-app/src/app/components/posts/posts.component.ts
  angular-app/src/app/components/series/series.component.ts
  angular-app/src/app/models/blog-info.ts
  angular-app/src/app/models/post.ts
  angular-app/src/app/services/blog.service.ts
Labels: 🐛 bug, 📁 file structure

#57 fix(pipe): using the builtin DomSanitizer pipe
  angular-app/src/app/components/post-details/post-details.component.html
  angular-app/src/app/components/post-details/post-details.component.ts
  angular-app/src/app/pipes/sanitizer-html.pipe.spec.ts
  angular-app/src/app/pipes/sanitizer-html.pipe.ts
Labels: 🐛 bug

#58 feature: Add right click open link in a new tab for individual blog posts in posts and series
  angular-app/src/app/components/posts/posts.component.html
  angular-app/src/app/components/posts/posts.component.ts
  angular-app/src/app/components/series/series.component.html
  angular-app/src/app/components/series/series.component.ts
Labels: 🐛 bug, 🌟feature

#60 feat: YouTube Videos Embed custom directive, fix: Dom Sanitizer Pipe
  angular-app/src/app/components/post-details/post-details.component.html
  angular-app/src/app/components/post-details/post-details.component.scss
  angular-app/src/app/components/post-details/post-details.component.ts
  angular-app/src/app/directives/clipboard-copy-button.directive.ts
  angular-app/src/app/directives/youtube-video-embed.directive.spec.ts
  angular-app/src/app/directives/youtube-video-embed.directive.ts
  angular-app/src/app/pipes/sanitizer-html.pipe.spec.ts
  angular-app/src/app/pipes/sanitizer-html.pipe.ts
Labels: 🐛 bug, 🌟feature, 🖼️ images & icons, 🔒 security, 🎨 styling, 📁 file structure, custom directive

#61 graphql operations
  angular-app/src/app/graphql.operations.ts
  angular-app/src/app/models/post.ts
Labels: 📁 file structure

#62 Publication id added
  angular-app/src/app/graphql.operations.ts
Labels: 📁 file structure

#72 feat(docs): issue templates yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 📄 documentation

#75 fix
  angular-app/src/index.html
Labels: 🐛 bug

#79 clearing up
  angular-app/src/app/app.routes.ts
  angular-app/src/app/components/post-details/post-details.component.ts
  angular-app/src/app/models/post.ts
  angular-app/src/app/partials/share-dialog/share-dialog.component.ts
  angular-app/src/app/services/blog.service.ts
Labels: code maintenance

#80 clearing up
  angular-app/src/app/services/blog.service.ts
Labels: code maintenance

#83 'post/' returned to route, wildcard redirect added
  angular-app/src/app/app.routes.ts
  angular-app/src/app/components/posts/posts.component.html
  angular-app/src/app/components/series/series.component.html
Labels: 🐛 bug, 🔀 routing

#86 trying some workflows
  .github/workflows/issue.yml
  .github/workflows/triage.yml
  angular-app/src/index.html
Labels: core team work

#89 Main
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/workflows/triage.yml
Labels: core team work

#90 update yml
  .github/workflows/triage.yml
Labels: core team work

#91 feat(docs): changelog generated
  angular-app/CHANGELOG.md
Labels: 📄 documentation

#95 feat(sitewide): initial responsiveness mobile media query
  angular-app/src/app/components/footer/footer.component.scss
  angular-app/src/app/components/header/header.component.scss
  angular-app/src/app/components/post-details/post-details.component.scss
  angular-app/src/app/components/posts/posts.component.scss
  angular-app/src/app/components/posts/posts.component.ts
  angular-app/src/app/components/series/series.component.scss
  angular-app/src/app/components/sidenav/sidenav.component.scss
  angular-app/src/app/partials/follow-dialog/follow-dialog.component.scss
  angular-app/src/app/partials/settings-dialog/settings-dialog.component.scss
  angular-app/src/app/partials/share-dialog/share-dialog.component.scss
  angular-app/src/app/partials/svg-icon/svg-icon.component.scss
  angular-app/src/styles.scss
Labels: 🌟feature, 📱responsiveness, 🎨 styling

#97 fix(responsiveness): corrections after view on actual device
  angular-app/src/app/components/header/header.component.scss
  angular-app/src/app/components/posts/posts.component.scss
  angular-app/src/app/components/series/series.component.scss
  angular-app/src/app/components/sidenav/sidenav.component.scss
  angular-app/src/app/partials/follow-dialog/follow-dialog.component.scss
  angular-app/src/app/partials/settings-dialog/settings-dialog.component.scss
  angular-app/src/app/partials/share-dialog/share-dialog.component.scss
  angular-app/src/styles.scss
Labels: 🐛 bug, 📱responsiveness, 🎨 styling

#98 fix(header): blog-title how it was supposed to be
  angular-app/src/app/components/header/header.component.html
Labels: core team work
