Repository AnguHashBlog/angular, pull requests merged in 2024-05, with the labels that each got.

#108 fix(settings-dialog): validations and error handling adjustment
  angular-app/src/app/partials/settings-dialog/settings-dialog.component.html
  angular-app/src/app/partials/settings-dialog/settings-dialog.component.ts
Labels: 🐛 bug, core team work

#111 feat(theme-switcher): custom theme switcher with icons & update 17.3.0
  angular-app/package-lock.json
  angular-app/package.json
  angular-app/src/app/components/header/header.component.html
  angular-app/src/app/components/header/header.component.ts
  angular-app/src/app/partials/theme-switcher/theme-switcher.component.html
  angular-app/src/app/partials/theme-switcher/theme-switcher.component.scss
  angular-app/src/app/partials/theme-switcher/theme-switcher.component.spec.ts
  angular-app/src/app/partials/theme-switcher/theme-switcher.component.ts
  angular-app/src/styles.scss
Labels: 🌟feature, 🖼️ images & icons, 🎨 styling, ☯️ theming, core team work

#115 Feature: Set the page position for post-details to always start at the very top OnInit
  angular-app/src/app/components/post-details/post-details.component.ts
Labels: 🌟feature

#117 fix(graphql.operations.ts): inconsistency in GraphQL query for author data
  angular-app/src/app/graphql.operations.ts
  angular-app/src/app/models/post.ts
Labels: 🐛 bug, 🛰️ apollo angular, GraphGL
